[package]
name = "game-of-life"
version = "1.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
opt-level = 3

[dependencies]
format_no_std = "1.0.2"
raylib = "3.7.0"
